/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.14 web.gltf 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'

export function Model(props) {
  const group = useRef()
  const anim = useRef();
  const { nodes, materials } = useGLTF('/logo/sourse/web.gltf')
  useFrame(({ clock }) => {
    const a = clock.getElapsedTime();
    anim.current.rotation.y = a / 3;
  })
  return (
    <group ref={anim} {...props} dispose={null}>
      <mesh geometry={nodes.Boole.geometry} material={materials['Material.001']} position={[0.007, 0, 0]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Cube.geometry} material={materials['Material.002']} position={[0.016, -0.016, 0]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
    </group>
  )
}

useGLTF.preload('/logo/sourse/web.gltf')
